# Generated by Django 5.2 on 2025-04-03 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(default='metric', max_length=10)),
                ('preferred_locations', models.ManyToManyField(to='weather.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(verbose_name='Температура (°C)')),
                ('feels_like', models.FloatField(verbose_name='Ощущается как (°C)')),
                ('humidity', models.FloatField(verbose_name='Влажность (%)')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (м/с)')),
                ('pressure', models.FloatField(verbose_name='Давление (мм рт. ст.)')),
                ('condition', models.CharField(max_length=100, verbose_name='Состояние')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
        ),
    ]
